version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_db
    environment:
      SA_PASSWORD: "YourStrong@Password" # ¡Cambia esto en producción!
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init.sql:/init.sql # Montamos el script en una ruta diferente
    command: >
      /bin/bash -c "
        (sleep 30 && /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong@Password' -C -i /init.sql) &
        /opt/mssql/bin/sqlservr
      "
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Password", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sqlserver_data:
