version: '3.8'

services:
  db-init:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db_init
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./init.sql:/init.sql
    command: /opt/mssql-tools18/bin/sqlcmd -S db -U sa -P "YourStrong@Password" -C -i /init.sql

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_db
    environment:
      SA_PASSWORD: "YourStrong@Password" # ¡Cambia esto en producción!
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Password", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file_processor_app
    environment:
      DB_HOST: db
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: "YourStrong@Password" # ¡Cambia esto en producción!
      DB_NAME: file_processor_db
      DB_SCHEMA: file_processor
    ports:
      - "3000:3000"
    depends_on:
      db-init:
        condition: service_completed_successfully
    volumes:
      - .:/app
      - /app/node_modules # Evita que el node_modules local sobreescriba el del contenedor
    command: sh -c "npm run typeorm:migration:run && npm run start:dev"

volumes:
  sqlserver_data:
