version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_db
    environment:
      SA_PASSWORD: "YourStrong@Password" # ¡Cambia esto en producción!
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Password", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file_processor_app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 1433
      DATABASE_USERNAME: sa
      DATABASE_PASSWORD: "YourStrong@Password" # ¡Cambia esto en producción!
      DATABASE_NAME: file_processor_db
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules # Evita que el node_modules local sobreescriba el del contenedor
    command: npm run start:dev # Opcional: para desarrollo, si no se usa nodemon dentro del contenedor

volumes:
  sqlserver_data:
